default:
  workspace:
    pwd1: 'Dutt16'
    pwd2: 'Brandner21'
    pwd3: 'Admin_22!'
    pwd4: 'General01'
    pwd5: 'Rispoli81'
  users:
    user1: 'Monika'
    user2: 'Sebastian'
    user3: 'Admin'
    user4: 'General'
    user5: 'Rossella'
  perms:
    perm1: 'admin'
    perm2: 'admin'
    perm3: 'admin'
    perm4: 'standard'
    perm5: 'admin'
  result_dirs:
    mnp_v12b8: 'classifier_reports'
    mnp_v12b6: 'classifier_reports'
    sarc_v12b6: 'classifier_reports'
    mnp_v11b4: 'classifier_reports'
    mnp_v11b6: 'classifier_reports'
    mnp_v11b8: 'classifier_reports'
    MEpurity_v0.1_c1: 'purity_estimates'
    MEpurity_v0.1_c2: 'purity_estimates'
    KIAA1549_BRAF_Fusion_v2.0_c2: 'KIAA_BRAF_results'
    KIAA1549_BRAF_Fusion_v2.0_c1: 'KIAA_BRAF_results'
    QC_v1_c1: 'QC_Reports'
    QC_v1_c2: 'QC_Reports'    
    Astrocytoma_v0.1_c1: 'Astrocytoma_results'
    Astrocytoma_v0.1_c2: 'Astrocytoma_results'
